# Generated by Django 4.1.4 on 2022-12-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bsthh', models.IntegerField()),
                ('bstmm', models.IntegerField()),
                ('bethh', models.IntegerField()),
                ('betmm', models.IntegerField()),
                ('ppd', models.IntegerField()),
                ('bstt', models.IntegerField()),
                ('bett', models.IntegerField()),
                ('totalslot', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='loginModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=12)),
                ('dateTime', models.DateTimeField()),
                ('otp', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientname', models.CharField(max_length=50)),
                ('patientage', models.IntegerField()),
                ('mobile', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
